"""Initial SiteSearch table

Revision ID: 17b3cdd5f40d
Revises: None
Create Date: 2013-05-24 18:48:52.793628

"""

# revision identifiers, used by Alembic.
revision = '17b3cdd5f40d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_search')
    ### end Alembic commands ###
