"""empty message

Revision ID: 18be85181c1e
Revises: 1672f08dd120
Create Date: 2013-11-20 23:38:19.666972

"""

# revision identifiers, used by Alembic.
revision = '18be85181c1e'
down_revision = '1672f08dd120'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Beta_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('date_activated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column(u'site_search', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column(u'users', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column(u'users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column(u'users', sa.Column('date_activated', sa.DateTime(), nullable=False))
    op.add_column(u'users', sa.Column('email', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'email')
    op.drop_column(u'users', 'date_activated')
    op.drop_column(u'users', 'email_confirmed')
    op.drop_column(u'users', 'activated')
    op.drop_column(u'site_search', 'user_id')
    op.drop_table('Beta_users')
    ### end Alembic commands ###
